pipeline {
  agent none
  environment {
    iris_bin = 'c:\\InterSystems\\IRIS\\bin\\'
    app_namespace = 'USER'
  }
  stages {
    stage('Install on Server') {
      agent { label 'server'}
       steps {
         // 成果物をコピー
        copyArtifacts projectName: 'build', target: 'kit'
        // キットをインストール
        bat '%iris_bin%loader kit\\IRISUtils.xml'
        // テストプログラムをロード、コンパイル
        bat '%iris_bin%loader -U %app_namespace% loader\\loadclass.xml src\\Test'
      }
    } 
    stage('Install on client') {
      agent { label 'client'}
       steps {
         // 成果物をコピー
        copyArtifacts projectName: 'build', target: 'kit'
        // キットをインストール
        bat '%iris_bin%loader kit\\IRISUtils.xml'
        // テストプログラムをロード、コンパイル
        bat '%iris_bin%loader -U %app_namespace% loader\\loadclass.xml src\\Test'
      }
    } 
    stage('Invoke client method') {
      agent { label 'client'}
       steps {
        dir('client_result')
        //クライアント側UnitTestを実行
        bat '%iris_bin%loader -U %app_namespace% loader\\execunittest.xml src\\UnitTest:UnitTest.CheckClient'
        junit 'result.xml'
      }
    } 
    stage('Check Data on Server') {
      agent { label 'server'}
       steps {
        // サーバにて受信したデータが正しいかをチェック
        dir('server_result') {
          bat "%iris_bin%loader -U %app_namespace% ..\\loader\\execunittest.xml src\\UnitTest:UnitTest.CheckServer"
          junit 'result.xml'
        }
      }
    }
  }
}
